### ISSUE TITLE
xterminal does not provide a default export

### ISSUE THREAD

**Issue by CHR-onicles** [henryhale/xterminal#36]
Hi, @henryhale 

I'm trying to integrate this into a Vite project, but I keep getting the following error:

```sh
[vite] Internal server error: [vite] The requested module 'xterminal' does not provide an export named 'default'
```
with the following import directly from the docs:
```ts
import XTerminal from "xterminal";
```

I try to import it as a named export, but I also get another saying there's no export by that name. My project uses ESM.

XTerminal version: 2.1.9
Vite version: 5.1.0

**Comment by henryhale** [comment]
Hey @CHR-onicles

I have looked into it and I'd like to help debug(fix) it. There is no enough information to spot the cause of the issue. The module, XTerminal v2.1.9, does provide a default export. 

To help debug the `xterminal` import issue, could you please provide the following?

- A minimal reproduction of the issue (small example code).
- Your `vite.config.js` and `package.json`.

This will help me better understand the problem and pinpoint the cause.

Here is a minimal reproduction using the specifics you provided;

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/stackblitz-starters-vqggzv1o)

Thanks!

**Comment by CHR-onicles** [comment]
Hey @henryhale,

I'm not going to be with my laptop till the weekend but I can provide the following. This is a Remix v2 project btw:


```ts
// vite.config.ts

import { vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import path from "path";
import svgr from "vite-plugin-svgr";

declare module "@remix-run/node" {
  interface Future {
    v3_singleFetch: true;
  }
}

export default defineConfig({
  plugins: [
    svgr(),
    remix({
      future: {
        v3_fetcherPersist: true,
        v3_relativeSplatPath: true,
        v3_throwAbortReason: true,
        v3_singleFetch: true,
        v3_lazyRouteDiscovery: true,
      },
    }),
    tsconfigPaths(),
  ],
  resolve: {
    alias: {
      // To prevent long relative imports in scss files
      "~/styles": path.resolve(__dirname, "./app/styles"),
    },
  },
  // to silence warnings from Sass
  css: {
    preprocessorOptions: {
      scss: {
        silenceDeprecations: ["legacy-js-api"],
      },
    },
  },
});
```

```json
// package.json
{
  "private": true,
  "sideEffects": false,
  "type": "module",
  "scripts": {
    "build": "remix vite:build",
    "dev": "remix vite:dev",
    "lint": "eslint --ignore-path .gitignore --cache --cache-location ./node_modules/.cache/eslint .",
    "start": "remix-serve ./build/server/index.js",
    "preview": "npm run build && npm run start",
    "tsc": "tsc"
  },
  "dependencies": {
    "@remix-run/node": "^2.15.1",
    "@remix-run/react": "^2.15.1",
    "@remix-run/serve": "^2.15.1",
    "isbot": "^4.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^2.15.1",
    "@types/react": "^18.2.20",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.7.4",
    "@typescript-eslint/parser": "^6.7.4",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.38.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-simple-import-sort": "^12.1.1",
    "postcss": "^8.4.38",
    "sass": "^1.83.0",
    "typescript": "^5.1.6",
    "vite": "^5.1.0",
    "vite-plugin-svgr": "^4.3.0",
    "vite-tsconfig-paths": "^4.2.1"
  },
  "engines": {
    "node": ">=20.0.0"
  }
}
```

```json
// tsconfig.json

{
  "include": [
    "**/*.ts",
    "**/*.tsx",
    "**/.server/**/*.ts",
    "**/.server/**/*.tsx",
    "**/.client/**/*.ts",
    "**/.client/**/*.tsx"
  ],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "types": ["@remix-run/node", "vite/client"],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "target": "ES2022",
    "strict": true,
    "allowJs": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"]
    },

    // Vite takes care of building everything, not tsc.
    "noEmit": true
  }
}

```

I hope this is helpful for now. By Sunday, I'll be fully available to help however I can :)

**Comment by henryhale** [comment]
Well, here is what is found: 

### root cause: remix vite plugin 
  > related issue: [https://github.com/remix-run/remix/issues/8507](https://github.com/remix-run/remix/issues/8507) 

The remix vite plugin issue is out of scope of this project but recommend checking out the following:
  - view docs: [https://remix.run/docs/en/main/guides/vite#esm--cjs](https://remix.run/docs/en/main/guides/vite#esm--cjs)
  - video: [https://www.youtube.com/watch?v=jmNuEEtwkD4](https://www.youtube.com/watch?v=jmNuEEtwkD4).

### issues within the scope of this project:
- the package is not published right: view issues - [https://publint.dev/xterminal@2.1.9](https://publint.dev/xterminal@2.1.9).
- types in the package have issues: [https://arethetypeswrong.github.io/?p=xterminal%402.1.9](https://arethetypeswrong.github.io/?p=xterminal%402.1.9)

I'm to fix the above issues with the package and keep in it's scope.

Thanks!

**Comment by CHR-onicles** [comment]
Thanks for the update @henryhale, can confirm it works without issues now. Also getting the proper types!
